apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NavabShariff1011/kubernetes-argo-cd
    targetRevision: master
    path: python-app
  destination:
    server: https://kubernetes.default.svc
    namespace: new
